#!/usr/bin/env bash

# Given a single-patient VCF file, create an "anonymous" version.
#
# The following fields are redacted:
#   id
#   reference (replaced with an equal number of As)
#   alternate (replaced with an equal number of Ts)
#   quality (set to 255)
#   info (set to ".")
#   genotype (set to heterozygous)
#
# The following fields are left unchanged:
#   chromosome
#   position
#
# Usage:
# A)  pipeline | anonymize-vcf > anonymous.vcf
# B)  anonymize-vcf patient.vcf > anonymous.vcf

set -o errexit
set -o nounset
set -o pipefail

awk -F"\t" 'BEGIN {OFS="\t"} /^#[^#]/ {$NF="SAMPLE"; print $0} /^[^#]/ {$3="."; $4=gensub("[a-zA-Z]", "A", "g", $4); $5=gensub("[a-zA-Z]", "T", "g", $5); $6=255; $8="."; $9="GT"; $10="0/1"; print $0}' "$@"